import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { Container, CssBaseline } from "@mui/material";
import Header from "./components/header/Header";
import Providers from "./providers";
import authenticated from "@/app/auth/action/authenticated.server";
import logout from "./auth/logout";

const kanit = Kanit({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await authenticated();
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>
        <Providers authenticated={isAuthenticated}>
          <CssBaseline />
          <Header logout={logout} />
          <Container className="mt-10">{children}</Container>
        </Providers>
      </body>
    </html>
  );
}
